version: '3'

services:
    builder:
        build:
            context: .
            dockerfile: Dockerfile.dev
        image: "rtnews/builder"
        container_name: "rtnews_builder"
        environment:
            # target of build, if not specified will be
            # "https://news.radio-t.com/api/v1" for production
            # and "http://jess.umputun.com:8780/api/v1"
            # for development
            - RTHOST
        ports:
            - "9000:9000"
        volumes:
            - ./src:/app/src:ro
            - ./@types:/app/@types:ro
            - ./makefile:/app/makefile:ro
            - ./tsconfig.json:/app/tsconfig.json:ro
            - ./testSetup:/app/testSetup:ro
            - ./webpack.config.js:/app/webpack.config.js:ro
            - ./jest.config.js:/app/jest.config.js:ro
            - ./sync-packages.sh:/app/sync-packages.sh:ro
            - ./package.json:/app/package.json.host
            - ./package-lock.json:/app/package-lock.json.host
            - ./public:/app/public
